---
title: "Age_Color_models"
author: "Ore, MJ."
date: "2025-03-20"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r prep data - age differences in color, echo = FALSE}

library(tidyverse)
library(here)
library(viridis)

here::i_am("R_scripts/Color_correlations.Rmd")

avg_img <- read.csv(here("data/BTBW_whole_specimen_Image_Analysis_measurements_allpop_avgimg_wide.csv"))

## select only brightness for ASY males
age <- avg_img %>% 
  filter(Age == "ASY" | Age == "SY")

```

# Crown
```{r crown, echo=F}

t <- t.test(dblMean_c ~ Age, data = age)

pval <- t$p.value
# Calculate means and confidence intervals
summary_stats <- age %>%
  group_by(Age) %>%
  summarise(
    mean = mean(dblMean_c, na.rm = T),
    stdev = sd(dblMean_c, na.rm = T)
  )

# Correct usage of sprintf to create the annotation text with standard deviation
text_annotation <- sprintf("ASY: %.3f ± %.3f, SY: %.3f ± %.3f, p-value: %.3f", summary_stats$mean[1], summary_stats$stdev[1], summary_stats$mean[2], summary_stats$stdev[2],pval)

ggplot(data = age, aes(y = dblMean_c, x = Age)) + 
  geom_boxplot(width = 0.6, position = position_dodge(width = 0.7)) +
  labs(x = "Age", y = "Mean Luminance of Crown") +
  annotate("text", x = Inf, y = Inf, label = text_annotation, 
           hjust = 1.1, vjust = 1.1, size = 5, color = "blue")+
  theme_classic() +
  theme(
    aspect.ratio = 0.75,
    text = element_text(size = 16),
    axis.text = element_text(size = 14)
  )

```

# coverts

```{r coverts, echo=F}

t <- t.test(dblMean_o ~ Age, data = age)

pval <- t$p.value
# Calculate means and confidence intervals
summary_stats <- age %>%
  group_by(Age) %>%
  summarise(
    mean = mean(dblMean_o, na.rm = T),
    stdev = sd(dblMean_o, na.rm = T)
  )

# Correct usage of sprintf to create the annotation text with standard deviation
text_annotation <- sprintf("ASY: %.3f ± %.3f, SY: %.3f ± %.3f, p-value: %.3f", summary_stats$mean[1], summary_stats$stdev[1], summary_stats$mean[2], summary_stats$stdev[2],pval)

ggplot(data = age, aes(y = dblMean_o, x = Age)) + 
  geom_boxplot(width = 0.6, position = position_dodge(width = 0.7)) +
  labs(x = "Age", y = "Mean Luminance of marginal coverts") +
  annotate("text", x = Inf, y = Inf, label = text_annotation, 
           hjust = 1.1, vjust = 1.1, size = 5, color = "blue")+
  theme_classic() +
  theme(
    aspect.ratio = 0.75,
    text = element_text(size = 16),
    axis.text = element_text(size = 14)
  )

```

#throat

```{r throat, echo=F}

t <- t.test(dblMean_t ~ Age, data = age)

pval <- t$p.value
# Calculate means and confidence intervals
summary_stats <- age %>%
  group_by(Age) %>%
  summarise(
    mean = mean(dblMean_t, na.rm = T),
    stdev = sd(dblMean_t, na.rm = T)
  )

# Correct usage of sprintf to create the annotation text with standard deviation
text_annotation <- sprintf("ASY: %.3f ± %.3f, SY: %.3f ± %.3f, p-value: %.3f", summary_stats$mean[1], summary_stats$stdev[1], summary_stats$mean[2], summary_stats$stdev[2],pval)

ggplot(data = age, aes(y = dblMean_t, x = Age)) + 
  geom_boxplot(width = 0.6, position = position_dodge(width = 0.7)) +
  labs(x = "Age", y = "Mean Luminance of Throat") +
  annotate("text", x = Inf, y = Inf, label = text_annotation, 
           hjust = 1.1, vjust = 1.1, size = 5, color = "blue")+
  theme_classic() +
  theme(
    aspect.ratio = 0.75,
    text = element_text(size = 16),
    axis.text = element_text(size = 14)
  )

```

# dorsum
```{r dorsum, echo=F}
t <- t.test(dblMean_d ~ Age, data = age)

pval <- t$p.value
# Calculate means and confidence intervals
summary_stats <- age %>%
  group_by(Age) %>%
  summarise(
    mean = mean(dblMean_d, na.rm = T),
    stdev = sd(dblMean_d, na.rm = T)
  )

# Correct usage of sprintf to create the annotation text with standard deviation
text_annotation <- sprintf("ASY: %.3f ± %.3f, SY: %.3f ± %.3f, p-value: %.3f", summary_stats$mean[1], summary_stats$stdev[1], summary_stats$mean[2], summary_stats$stdev[2],pval)


ggplot(data = age, aes(y = dblMean_d, x = Age)) + 
  geom_boxplot(width = 0.6, position = position_dodge(width = 0.7)) +
  labs(x = "Age", y = "Mean Luminance of Dorsum") +
  annotate("text", x = Inf, y = Inf, label = text_annotation, 
           hjust = 1.1, vjust = 1.1, size = 5, color = "blue")+
  theme_classic() +
  theme(
    aspect.ratio = 0.75,
    text = element_text(size = 16),
    axis.text = element_text(size = 14)
  )


```

#belly
```{r belly, echo=F}

t <- t.test(dblMean_b ~ Age, data = age)

pval <- t$p.value
# Calculate means and confidence intervals
summary_stats <- age %>%
  group_by(Age) %>%
  summarise(
    mean = mean(dblMean_b, na.rm = T),
    stdev = sd(dblMean_b, na.rm = T)
  )

# Correct usage of sprintf to create the annotation text with standard deviation
text_annotation <- sprintf("ASY: %.3f ± %.3f, SY: %.3f ± %.3f, p-value: %.3f", summary_stats$mean[1], summary_stats$stdev[1], summary_stats$mean[2], summary_stats$stdev[2],pval)

ggplot(data = age, aes(y = dblMean_b, x = Age)) + 
  geom_boxplot(width = 0.6, position = position_dodge(width = 0.7)) +
  labs(x = "Age", y = "Mean Luminance of Belly") +
  annotate("text", x = Inf, y = Inf, label = text_annotation, 
           hjust = 1.1, vjust = 1.1, size = 5, color = "blue")+
  theme_classic() +
  theme(
    aspect.ratio = 0.75,
    text = element_text(size = 16),
    axis.text = element_text(size = 14)
  )


```

# wingspot
```{r wingspot lum, echo=F}

t <- t.test(dblMean_w ~ Age, data = age)

pval <- t$p.value

# Calculate means and confidence intervals
summary_stats <- age %>%
  group_by(Age) %>%
  summarise(
    mean = mean(dblMean_w, na.rm = T),
    stdev = sd(dblMean_w, na.rm = T)
  )

# Correct usage of sprintf to create the annotation text with standard deviation
text_annotation <- sprintf("ASY: %.3f ± %.3f, SY: %.3f ± %.3f, p-value: %.3f", summary_stats$mean[1], summary_stats$stdev[1], summary_stats$mean[2], summary_stats$stdev[2],pval)

ggplot(data = age, aes(y = dblMean_w, x = Age)) + 
  geom_boxplot(width = 0.6, position = position_dodge(width = 0.7)) +
  labs(x = "Age", y = "Mean Luminance of wingspot (brightness)") +
  annotate("text", x = Inf, y = Inf, label = text_annotation, 
           hjust = 1.1, vjust = 1.1, size = 5, color = "blue")+
  theme_classic() +
  theme(
    aspect.ratio = 0.75,
    text = element_text(size = 16),
    axis.text = element_text(size = 14)
  )

```


```{r wingspot area}

t <- t.test(area_mm2_w ~ Age, data = age)


pval <- t$p.value
# Calculate means and confidence intervals
summary_stats <- age %>%
  group_by(Age) %>%
  summarise(
    mean = mean(area_mm2_w, na.rm = T),
    stdev = sd(area_mm2_w, na.rm = T)
  )

# Correct usage of sprintf to create the annotation text with standard deviation
text_annotation <- sprintf("ASY: %.3f ± %.3f, SY: %.3f ± %.3f, p-value: %.3f", summary_stats$mean[1], summary_stats$stdev[1], summary_stats$mean[2], summary_stats$stdev[2],pval)


ggplot(data = age, aes(y = area_mm2_w, x = Age)) + 
  geom_boxplot(width = 0.6, position = position_dodge(width = 0.7)) +
  labs(x = "Age", y = "Area of wingspot (mm2)") +
  annotate("text", x = Inf, y = Inf, label = text_annotation, 
           hjust = 1.1, vjust = 1.1, size = 5, color = "blue")+
  theme_classic() +
  theme(
    aspect.ratio = 0.75,
    text = element_text(size = 16),
    axis.text = element_text(size = 14)
  )


```

# make a table of results
```{r age table, echo=F}

summary_stats <- age %>%
  group_by(Age) %>%
  summarise(
    lum_b = paste0(signif(mean(lumMean_b, na.rm = T), digits = 3), 
                   " (±",
                   signif(mean(lumSD_b, na.rm = T), digits=2), ")"),
    lum_c = paste0(signif(mean(lumMean_c, na.rm = T), digits = 3), 
                   " (±",
                   signif(mean(lumSD_c, na.rm = T), digits=2), ")"),
    lum_d = paste0(signif(mean(lumMean_d, na.rm = T), digits = 3), 
                   " (±",
                   signif(mean(lumSD_d, na.rm = T), digits=2), ")"),
    lum_o = paste0(signif(mean(lumMean_o, na.rm = T), digits = 3), 
                   " (±",
                   signif(mean(lumSD_o, na.rm = T), digits=2), ")"),
    lum_t = paste0(signif(mean(lumMean_t, na.rm = T), digits = 3), 
                   " (±",
                   signif(mean(lumSD_t, na.rm = T), digits=2), ")"),
    lum_w = paste0(signif(mean(lumMean_w, na.rm = T), digits = 3), 
                   " (±",
                   signif(mean(lumSD_w, na.rm = T), digits=2), ")"),
    area_mm2_w = paste0(signif(mean(area_mm2_w, na.rm = T), digits = 3), 
                   " (±",
                   signif(sd(area_mm2_w, na.rm = T), digits=2), ")"),
  )


sum_stats <- as.data.frame(t(summary_stats))
# Set the first row as column names
colnames(sum_stats) <- sum_stats[1, ]

# Remove the first row (now redundant)
sum_stats <- sum_stats[-1, ]


# get t.test pvals
# get df with just relevant variables
age_sel <- age %>% 
  dplyr::select(Age, lumMean_b, lumMean_c, lumMean_d, lumMean_o, lumMean_t, lumMean_w, area_mm2_w)
# Split the data by group
grouped_age <- split(age_sel, age_sel$Age)

# Run t-tests for each variable (excluding the group column)
variables <- names(age_sel)[names(age_sel) != "Age"]
p_values <- sapply(variables, function(var) {
  t.test(grouped_age$ASY[[var]], grouped_age$SY[[var]])$p.value
})


sumstats_p <- cbind(sum_stats, p = signif(p_values, digits =3))

sumstats_p

```