---
title: "Are dark-backed birds darker overall?"
author: "Ore, MJ."
date: "2025-03-10"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r prep data - geographic variation in color, echo = FALSE}

library(tidyverse)
library(here)
library(viridis)

here::i_am("R_scripts/Color_correlations.Rmd")


avg_img <- read.csv(here("data/BTBW_whole_specimen_Image_Analysis_measurements_allpop_avgimg_wide.csv"))

## select only brightness for ASY males
asy <- avg_img %>% 
  filter(Age == "ASY")



```
How do luminance and shortwavelength correlate
```{r sw vs lum, echo =F }

lumsw <- asy %>% 
  dplyr::select(starts_with("lumMean"), starts_with("swMean"))

# Extract unique letters from column names
letters <- gsub(".*_", "", names(lumsw)[grepl("lumMean_", names(lumsw))])

# Calculate correlations for matching columns
correlations <- sapply(letters, function(letter) {
  lum_col <- paste0("lumMean_", letter)
  sw_col <- paste0("swMean_", letter)
  cor(lumsw[[lum_col]], lumsw[[sw_col]], use = "complete.obs")
})

# Convert to a data frame
correlation_df <- data.frame(
  Letter = letters,
  Correlation = correlations
)


```

#crown

```{r crown, echo = F}
library(lmerTest)
library(MuMIn)
library(sjPlot)

# check for normality
hist(asy$PC1_d)
hist(asy$PC1_c)

z <- lmerTest::lmer(PC1_c ~ PC1_d + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(z)

r.squaredGLMM(z)
tab_model(z)

ggplot(asy)+
  geom_point(aes(x = PC1_d, y = PC1_c, col = lat))+
  scale_color_viridis_c(direction = -1)+
  geom_smooth(aes(x = PC1_d, y = PC1_c), method = "lm", col = "black")+
  labs(x = "Dorsum PC1", y = "Crown PC1")+
  theme_classic()

```

#wingspot

```{r wingspot}

library(lmerTest)
library(MuMIn)
library(sjPlot)

# check for normality
hist(asy$PC1_d)
hist(asy$PC1_w)

z <- lmerTest::lmer(PC1_w ~ PC1_d + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(z)

r.squaredGLMM(z)
tab_model(z)

dVw <- ggplot(asy)+
  geom_point(aes(x = PC1_d, y = PC1_w, col = lat), size = 6)+
  scale_color_viridis_c(direction = -1)+
  geom_smooth(aes(x = PC1_d, y = PC1_w), method = "lm", col = "black")+
  labs(x = "Dorsum PC1", y = "Wingspot PC1")+
  theme_classic()+
  theme(text=element_text(size=20))  

dVw

ggsave(plot = dVw, here("results/WingspotVSDorsum_plot.png"), dpi = 600, width = 8, height = 6)

z <- lmerTest::lmer(area_mm2_w ~ PC1_d + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(z)

r.squaredGLMM(z)
tab_model(z)

ggplot(asy)+
  geom_point(aes(x = PC1_d, y = area_mm2_w, col = lat))+
  scale_color_viridis_c(direction = -1)+
  geom_smooth(aes(x = PC1_d, y = area_mm2_w), method = "lm", col = "black")+
  labs(x = "Dorsum PC1", y = "Wingspot area (mm2)")+
  theme_classic()

```

#throat

```{r throat}

library(lmerTest)
library(MuMIn)
library(sjPlot)

# check for normality
hist(asy$PC1_d)
hist(asy$PC1_t)

z <- lmerTest::lmer(PC1_t ~ PC1_d + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(z)

r.squaredGLMM(z)
tab_model(z)

ggplot(asy)+
  geom_point(aes(x = PC1_d, y = PC1_t, col = lat))+
  scale_color_viridis_c(direction = -1)+
  geom_smooth(aes(x = PC1_d, y = PC1_t), method = "lm", col = "black")+
  labs(x = "Dorsum PC1", y = "Throat PC1")+
  theme_classic()

```

#marginal covert

```{r coverts}

library(lmerTest)
library(MuMIn)
library(sjPlot)

# check for normality
hist(asy$PC1_d)
hist(asy$PC1_o)

z <- lmerTest::lmer(PC1_o ~ PC1_d + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(z)

r.squaredGLMM(z)
tab_model(z)

ggplot(asy)+
  geom_point(aes(x = PC1_d, y = PC1_o, col = lat))+
  scale_color_viridis_c(direction = -1)+
  geom_smooth(aes(x = PC1_d, y = PC1_o), method = "lm", col = "black")+
  labs(x = "Dorsum PC1", y = "Covert PC1")+
  theme_classic()

```

#belly

```{r belly}

library(lmerTest)
library(MuMIn)
library(sjPlot)

# check for normality
hist(asy$PC1_d)
hist(asy$PC1_b)

z <- lmerTest::lmer(PC1_b ~ PC1_d + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(z)

r.squaredGLMM(z)
tab_model(z)

ggplot(asy)+
  geom_point(aes(x = PC1_d, y = PC1_b, col = lat))+
  scale_color_viridis_c(direction = -1)+
  geom_smooth(aes(x = PC1_d, y = PC1_b), method = "lm", col = "black")+
  labs(x = "Dorsum PC1", y = "Belly PC1")+
  ylim(0.3,0.6)+
  theme_classic()

```

#throat vs wingspot

```{r throat v wingspot}

library(lmerTest)
library(MuMIn)
library(sjPlot)

# check for normality
hist(asy$PC1_t)
hist(asy$PC1_w)

z <- lmerTest::lmer(PC1_w ~ PC1_t + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(z)

r.squaredGLMM(z)
tab_model(z)

ggplot(asy)+
  geom_point(aes(x = PC1_t, y = PC1_w, col = lat))+
  scale_color_viridis_c(direction = -1)+
  geom_smooth(aes(x = PC1_t, y = PC1_w), method = "lm", col = "black")+
  labs(x = "Throat PC1", y = "Wingspot PC1")+
  theme_classic()



z <- lmerTest::lmer(area_mm2_w ~ PC1_t + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(z)

r.squaredGLMM(z)
tab_model(z)

ggplot(asy)+
  geom_point(aes(x = PC1_t, y = area_mm2_w, col = lat))+
  scale_color_viridis_c(direction = -1)+
  geom_smooth(aes(x = PC1_t, y = area_mm2_w), method = "lm", col = "black")+
  labs(x = "Throat PC1", y = "Wingspot area (mm2)")+
  theme_classic()

```

# wingspot vs other plumage patches

```{r wingspot v}

crown <- lmerTest::lmer(PC1_c ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(crown)

covert <- lmerTest::lmer(PC1_o ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(covert)

belly <- lmerTest::lmer(PC1_b ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(belly)

throat <- lmerTest::lmer(PC1_t ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(throat)

tvc <- lmerTest::lmer(PC1_t ~ PC1_o + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
summary(tvc)

```

# make a table of results
```{r color model table, echo=F}

library(lmerTest)
library(MuMIn)

#association with dorsum
cd <- lmerTest::lmer(PC1_c ~ PC1_d + (1|Year) + (1|prepartor), data = asy, 
                       na.action = na.exclude)
td <- lmerTest::lmer(PC1_t ~ PC1_d + (1|Year) + (1|prepartor), data = asy, 
                       na.action = na.exclude)
od <- lmerTest::lmer(PC1_o ~ PC1_d + (1|Year) + (1|prepartor), data = asy, 
                       na.action = na.exclude) 
bd <- lmerTest::lmer(PC1_b ~ PC1_d + (1|Year) + (1|prepartor), data = asy, 
                       na.action = na.exclude) 
#associations with wing spot color
cwpc <- lmerTest::lmer(PC1_c ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
owpc <- lmerTest::lmer(PC1_o ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
bwpc <- lmerTest::lmer(PC1_b ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
dwpc <- lmerTest::lmer(PC1_d ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude)
twpc <- lmerTest::lmer(PC1_t ~ PC1_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
#association with wing spot area
cwa <- lmerTest::lmer(PC1_c ~ area_mm2_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude)
owa <- lmerTest::lmer(PC1_o ~ area_mm2_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude)
bwa <- lmerTest::lmer(PC1_b ~ area_mm2_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude)
dwa <- lmerTest::lmer(PC1_d ~ area_mm2_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude)
twa <- lmerTest::lmer(PC1_t ~ area_mm2_w + (1|Year) + (1|prepartor), data = asy, na.action = na.exclude) 
models <- c(cd, od, bd, td, cwpc, owpc, bwpc, dwpc, twpc, cwa, owa, bwa, dwa, twa)

# Initialize an empty data frame to store results
results <- data.frame(
  Response = character(),
  Explanatory = character(),
  P_value = numeric(),
  R2m = numeric(),
  stringsAsFactors = FALSE
)

# Loop through each model
for (model_name in 1:length(models)) {
  model <- models[[model_name]]
  
  # Extract response variable
  response <- as.character(formula(model)[[2]])
  
  # Extract explanatory variables
  explanatory <- paste(as.character(formula(model)[[3]]), collapse = " + ")
  
  # Extract marginal R² (R2m)
  r_squared <- MuMIn::r.squaredGLMM(model)
  R2m <- r_squared[1]  # Marginal R²
  
  # Extract p-value for the first fixed effect
  summary_model <- summary(model)
  p_value <- summary_model$coefficients[2, "Pr(>|t|)"]  # Adjust index for the variable of interest
  
  # Add results to the data frame
  results <- rbind(results, data.frame(
    Response = response,
    Explanatory = explanatory,
    R2m = R2m,
    P_value = p_value,
    stringsAsFactors = FALSE
  ))
}

results_rounded <- results %>% 
   mutate(across(where(is.numeric), ~ ifelse(. < 0.001, format(., scientific = TRUE, digits = 3),
                                           round(., 3))))
#change names for table presentation
pcnames <- c(
  "PC1_c" = "Crown PC1",
  "PC1_o" = "Covert PC1",
  "PC1_b" = "Belly PC1",
  "PC1_d" = "Dorsum PC1",
  "PC1_t" = "Throat PC1",
  "PC1_w" = "Wing spot PC1"
)

formnames <- c(
  "+ + PC1_d + (1 | Year) + (1 | prepartor)" = "~Dorsum PC1 + (1|Year) + (1|preparator)",
  "+ + PC1_w + (1 | Year) + (1 | prepartor)" = "~Wing spot PC1 + (1|Year) + (1|preparator)",
  "+ + area_mm2_w + (1 | Year) + (1 | prepartor)" = "~Wing spot area + (1|Year) + (1|preparator)"
)

results_rnm <- results_rounded %>%
  mutate(Response = recode(Response, !!!pcnames)) %>% 
  mutate(Explanatory = recode(Explanatory, !!!formnames))
# View the results
print(results_rnm)

write.csv(results_rnm, file = here("results/Color_lmm_model_results.csv"), row.names = F)

```