---
title: "Dorsum_environment"
author: "Ore, MJ."
date: "2025-03-11"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prep data, echo = FALSE}

library(tidyverse)
library(here)
library(viridis)

here::i_am("R_scripts/Color_correlations.Rmd")


avg_img <- read.csv(here("data/BTBW_whole_specimen_Image_Analysis_measurements_allpop_avgimg_wide.csv"))

## select only brightness for ASY males
asy <- avg_img %>% 
  filter(Age == "ASY") 

# combine w environment data  
env <- read.table(here("data/Env_by_individual_specimen_samples.txt"), header = T) %>% 
  dplyr::select(-Year)

lum_env <- merge(asy, env) %>% 
  filter(!is.na(PC1_d))

```

## Does location predict color ? 

```{r spatio-temporal fit, echo = F}

library(mgcv)
library(lmerTest)
library(MuMIn)

#perform linear regression
z <- lm(PC1_d~lat, data = asy, na.action = na.exclude)
sum_z <- summary(z)

# Extract the r^2 and p-value
r2adj <- sum_z$adj.r.squared
p_value <- sum_z$coefficients[2, "Pr(>|t|)"]

# Format the text to include rho and p-value, ready to be used in annotations
text_annotation <- bquote("Adjusted R"^2 ~ ": " ~ .(sprintf("%.2f", r2adj)) ~ ", p-value: " ~ .(sprintf("%.3f", p_value)))


ggplot(data = asy, aes(x = lat, y = PC1_d)) + 
  geom_point(width = 0.6, position = position_dodge(width = 0.7)) +
  labs(x = "Latitude", y = "Luminance (brightness)") +
  geom_smooth(aes(x = lat, y = PC1_d), method = "lm", col = "black")+
  theme_classic() +
  annotate("text", x = Inf, y = Inf, label = text_annotation, 
           hjust = 1.1, vjust = 1.1, size = 5, color = "blue")+
  theme(
    aspect.ratio = 0.75,
    text = element_text(size = 16),
    axis.text = element_text(size = 14)
  )


## spatio-temporal fit
mod2d <- gam(PC1_d ~ s(lon, lat), 
                data = lum_env)
mod2dbyY <- gam( PC1_d ~ s(lon, lat, by = Year), 
                data = lum_env)
mod2dYY <- gam( PC1_d ~ s(lon, lat, by = Year) + Year,
               data = lum_env)
mod2dY <- gam( PC1_d ~ s(lon, lat) + Year, method = "REML",
                   data = lum_env) 
modnull <- lm(PC1_d ~ 1, data = lum_env) 
modlmlat_randY <- lmerTest::lmer(PC1_d ~ lat + (1|Year) + (1|prepartor),
                    data = lum_env, REML = T) 
modlmlatY <- lmerTest::lmer(PC1_d ~ lat + Year + (1|prepartor),
                    data = lum_env, REML = T) 
modlmY <- lm(PC1_d ~ Year, data = lum_env, REML = T) 


aicsc <- AICc(mod2d ,mod2dbyY, mod2dYY, mod2dY,
              modnull, modlmlat_randY, modlmlatY, modlmY)
aicsc$deltaic <- aicsc$AIC - min(aicsc$AIC)
aicsc$weights <- Weights(AICc(mod2d ,mod2dbyY, mod2dYY, mod2dY, 
              modnull, modlmlat_randY, modlmlatY,modlmY))

mod_names <- c("mod2d" ,"mod2dbyY", "mod2dYY", "mod2dY", 
              "modnull", "modlmlat_randY", "modlmlatY", "modlmY")
# Extract formulas as a character vector
aicsc$formulas <- lapply(mod_names, function(model_name) {
  model <- get(model_name)  # Retrieve the model object by name
  paste(deparse(formula(model)), collapse = " ")  # Convert the formula to a single string
}) 

aicsc_r <- aicsc %>%
  mutate(
    MarginalR2 = sapply(mod_names, function(model_name) {
      model <- get(model_name)  # Retrieve the model object by name
      if (inherits(model, "lmerMod")) {
        r.squaredGLMM(model)[1]  # Extract marginal R²
      } else {
        NA  # Return NA for non-lmer models
      }
    }),
    ConditionalR2 = sapply(mod_names, function(model_name) {
       model <- get(model_name)  # Retrieve the model object by name
      if (inherits(model, "lmerMod")) {
        r.squaredGLMM(model)[2]  # Extract conditional R²
      } else {
        NA  # Return NA for non-lmer models
      }
    })
  )

aicsc_r$formulas <- as.character(aicsc_r$formulas)
aicsc_r$df <- round(aicsc_r$df, digits = 2)
aicsc_r$AICc <- round(aicsc_r$AICc, digits = 2)
aicsc_r$deltaic <- round(aicsc_r$deltaic, digits = 2)
aicsc_r$weights <- signif(aicsc_r$weights, digits = 2)
aicsc_r$MarginalR2 <- signif(aicsc_r$MarginalR2, digits = 2)
aicsc_r$ConditionalR2 <- signif(aicsc_r$ConditionalR2, digits = 2)


model_results <- aicsc_r %>% 
  arrange(deltaic) %>% 
  dplyr::select(formulas, everything()) 

model_results

write.csv(model_results, here("results/spatiotemp_model_selection_table.csv"), row.names = F)

```

# Build model for env-dorsum correlation

```{r lmm pheno-env, echo = F}

library(lmerTest)
library(MASS)
library(MuMIn)
library(performance)
library(sjPlot)


options(na.action = "na.fail")

z <- lmerTest::lmer(PC1_d ~ PPT_br + RH_br + Tave_br + lat + lon + srtm + 
                      ndvi_M + (1|Year) + (1|prepartor),
                    data = lum_env, REML = T) 



check_model(z)
summary(z)
tab_model(z)

# Model selection: ranking by AICc using ML
ms2 <- dredge(z, trace = TRUE, rank = "AICc", REML = F)

print(ms2)                                  # Model selection table
bestmods <- ms2[ms2$delta < 5]                    # Tabulate only models with AIC difference < 5
Weights(ms2)                                # AIC weights all models
Weights(ms2[ms2$delta < 5])                   # Include only models with AIC difference < 5
get.models(ms2, subset=delta<5)  # Extract the models having AIC difference < 5
get.models(ms2, subset = 1)[[1]]            # Extract single best model (yields lm object)

lmter <- lm(get.models(ms2, subset = 1)[[1]], data = lum_env) # Fit best model
summary(model.avg(ms2, subset = delta < 2))              # model averaging


```

```{r random forest pheno-env, echo = F}

library(randomForest)


model <- PC1_d ~ PPT_br + RH_br + Tave08_molt + srtm  + ndvi_M + lat

rf1 <- randomForest(model, data = lum_env,
              ntreeTry=500,
               mtryStart=4, 
               stepFactor=1.5,
               improve=0.01,
               trace=FALSE #don't show real-time progress
               )
which.min(rf1$mse)
sqrt(rf1$mse[which.min(rf1$mse)])
plot(rf1)
randomForest::importance(rf1)
varImpPlot(rf1)


```

## Generalized Additive Model

```{r GAM, echo = F}

library(mgcv)
library(itsadug)

mod2dY <- gam( PC1_d ~ s(lon, lat) + Year, method = "REML",
                   data = lum_env) 
full <- gam(PC1_d ~ s(lon, lat) + s(RH_br) + s(Tave_br) +
                + s(PPT_br) + s(srtm) + s(ndvi_M), select = T, 
            data = lum_env, method = "REML") 
nospace <- gamm(PC1_d ~ Year + s(RH_br) + s(Tave_br) +
                + s(PPT_br) + s(srtm) + s(ndvi_M), random = list(pop = ~1),
                select = T, 
            data = lum_env, method = "REML")

## make table with results

# Extract summary
full_summary <- summary(full)

# Convert smooth terms to a data frame
full_smooth <- as.data.frame(full_summary$s.table)
full_smooth <- cbind(Term = rownames(full_smooth), full_smooth)
rownames(full_smooth) <- NULL
#convert params to df
full_param <- as.data.frame(full_summary$p.table) %>% 
  rename(`p-value` = `Pr(>|t|)`)
full_param <- cbind(Term = rownames(full_param), full_param)
rownames(full_param) <- NULL
#combine and name
full_table <- merge(full_smooth, full_param, all = T)
full_table$model_name <- rep("Full", nrow(full_table))

# Extract summary
spt_summary <- summary(mod2dY)

# Convert smooth terms to a data frame
spt_table <- as.data.frame(spt_summary$s.table)
spt_table <- cbind(Term = rownames(spt_table), spt_table)
rownames(spt_table) <- NULL
#convert params to df
param_table <- as.data.frame(spt_summary$p.table) %>% 
  rename(`p-value` = `Pr(>|t|)`)
param_table <- cbind(Term = rownames(param_table), param_table)
rownames(param_table) <- NULL
#combine and name
spt_param <- merge(spt_table, param_table, all = T)
spt_param$model_name <- rep("Spatiotemporal", nrow(spt_param))


spt_full <- merge(spt_param, full_table, all = T) %>% 
  dplyr::arrange(desc(model_name)) %>%  
  dplyr::select(model_name, everything()) %>% 
  mutate(across(where(is.numeric), ~ round(., 2)))

spt_full$`p-value`[which(spt_full$`p-value` < 0.001)] <- "<0.001"
spt_full

write.csv(spt_full, here("results/Env_gam_model_results.csv"), row.names = F)
```

## GAM vs other plumage patches

```{r other gams}
library(mgcv)

belly <- gam(PC1_b ~ s(lon, lat) + s(RH_br) + s(Tave_br) +
                + s(PPT_br) + s(srtm) + s(ndvi_M), select = T, 
            data = lum_env, method = "REML", na.action = "na.omit") 
summary(belly)

crown <- gam(PC1_c ~ s(lon, lat) + s(RH_br) + s(Tave_br) +
                + s(PPT_br) + s(srtm) + s(ndvi_M), select = T, 
            data = lum_env, method = "REML", na.action = "na.omit") 
summary(crown)

covert <- gam(PC1_o ~ s(lon, lat) + s(RH_br) + s(Tave_br) +
                + s(PPT_br) + s(srtm) + s(ndvi_M), select = T, 
            data = lum_env, method = "REML", na.action = "na.omit") 
summary(covert)

throat <- gam(PC1_t ~ s(lon, lat) + s(RH_br) + s(Tave_br) +
                + s(PPT_br) + s(srtm) + s(ndvi_M), select = T, 
            data = lum_env, method = "REML", na.action = "na.omit") 
summary(throat)

wspot <- gam(PC1_w ~ s(lon, lat) + s(RH_br) + s(Tave_br) +
                + s(PPT_br) + s(srtm) + s(ndvi_M), select = T, 
            data = lum_env, method = "REML", na.action = "na.omit") 
summary(wspot)




```

```{r table env vs plumage}
library(dplyr)

pl_gams <- list(belly = belly, crown = crown, covert = covert, throat =  throat, wspot = wspot)

# Extract smooth and parametric terms for each GAM
gam_tables <- lapply(pl_gams, function(model) {
  # Get the summary of the model
  model_summary <- summary(model)
  
  # Extract smooth terms
  smooth_terms <- as.data.frame(model_summary$s.table)
  smooth_terms <- cbind(Term = rownames(smooth_terms), smooth_terms)
  rownames(smooth_terms) <- NULL

  return(smooth_terms)
})


combined_gam <- bind_rows(gam_tables, .id = "Model")%>% 
 mutate(across(where(is.numeric), ~ ifelse(. < 0.001, format(., scientific = TRUE, digits = 3),
                                           round(., 2))))


write.csv(combined_gam, here("results/GAM_for_other_pl_patches.csv"), row.names = F)

```

```{r plot}
library(tidyverse)
library(patchwork)
library(viridis)

srtm_fit <- data.frame(
  srtm = seq(min(lum_env$srtm), max(lum_env$srtm), length.out = 100),
  lat = mean(lum_env$lat),
  lon = mean(lum_env$lon),
  RH_br = mean(lum_env$RH_br),
  Tave_br = mean(lum_env$Tave_br),
  PPT_br = mean(lum_env$PPT_br),
  ndvi_M = mean(lum_env$ndvi_M)
)

predictions <- predict(full, newdata = srtm_fit, se.fit = TRUE)

# Add predictions and confidence intervals to the new data frame
srtm_fit$PC1_d_pred <- predictions$fit
srtm_fit$lower_CI <- predictions$fit - 1.96 * predictions$se.fit  # 95% lower bound
srtm_fit$upper_CI <- predictions$fit + 1.96 * predictions$se.fit  # 95% upper bound

elev <- ggplot(data = lum_env, aes(x = srtm, y = PC1_d, color = lat)) +
  geom_point(size = 4) +  # Observed data
  scale_color_viridis_c(direction = -1)+
  geom_line(data = srtm_fit, aes(x = srtm, y = PC1_d_pred), size = 1, color = "black") +  
  geom_ribbon(data = srtm_fit, aes(x = srtm, ymin = lower_CI, ymax = upper_CI),
              alpha = 0.2, inherit.aes = FALSE) +  # Confidence intervals
  labs(x = "Elevation", y = "PC1 Dorsum") +
  theme_classic()+
  theme(text=element_text(size=24))  


tave_fit <- data.frame(
  srtm = mean(lum_env$srtm),
  lat = mean(lum_env$lat),
  lon = mean(lum_env$lon),
  RH_br = mean(lum_env$RH_br),
  Tave_br = seq(min(lum_env$Tave_br), max(lum_env$Tave_br), length.out = 100),
  PPT_br = mean(lum_env$PPT_br),
  ndvi_M = mean(lum_env$ndvi_M)
)

predictions <- predict(full, newdata = tave_fit, se.fit = TRUE)

# Add predictions and confidence intervals to the new data frame
tave_fit$PC1_d_pred <- predictions$fit
tave_fit$lower_CI <- predictions$fit - 1.96 * predictions$se.fit  # 95% lower bound
tave_fit$upper_CI <- predictions$fit + 1.96 * predictions$se.fit  # 95% upper bound

temp <- ggplot(data = lum_env, aes(x = Tave08_molt, y = PC1_d, color = lat))+
  geom_point(size = 4)+
  scale_color_viridis_c(direction = -1)+
  labs(x = "Mean Temperature during molt", y = "PC1 Dorsum")+
  geom_line(data = tave_fit, aes(x = Tave_br, y = PC1_d_pred, color = lat), size = 1) +  
  geom_ribbon(data = tave_fit, aes(x = Tave_br, ymin = lower_CI, ymax = upper_CI),
              alpha = 0.2, inherit.aes = FALSE) +  # Confidence intervals
  guides(color = "none") +
  theme_classic()+
  theme(text=element_text(size=24))  




latplot <- ggplot(data = lum_env, aes(x = lat, y = PC1_d, color = lat))+
  geom_point(size = 4)+
  scale_x_reverse()+
  scale_color_viridis_c(direction = -1)+
  labs(x = "Latitude", y = "PC1 Dorsum")+
  guides(color = "none") +
  geom_smooth(aes(x = lat, y = PC1_d), method = "lm", col = "black")+
  theme_classic()+
  theme(text=element_text(size=24))  

# Combine plots into 1 row and 3 columns with labels
env_plots <- (latplot + temp + elev) +
  plot_annotation(tag_levels = "A")+  # Adds labels A, B, C
  plot_layout(axis_titles = "collect")

env_plots

ggsave(here("results/top_env_plots.png"), plot = env_plots, width = 24, height = 8, dpi = 600)

```

#relationship between latitude and environment

```{env and lat}

ggplot(data = lum_env, aes(x = srtm, y = PPT_br, color = lat))+
  geom_point(size = 6)+
  theme_classic()
ggplot(data = lum_env, aes(x = srtm, y = Tave_br, color = lat))+
  geom_point(size = 6)+
  theme_classic()
ggplot(data = lum_env, aes(x = lat, y = PPT_br, color = lat))+
  geom_point(size = 6)+
  theme_classic()
ggplot(data = lum_env, aes(x = lat, y = RH_br, color = lat))+
  geom_point(size = 6)+
  theme_classic()

latppt <- lm(PPT_br~lat, data = lum_env)
latelev <- lm(srtm~lat, data = lum_env)
lattemp <- lm(Tave_br~lat, data = lum_env)
latrh <- lm(RH_br~lat, data = lum_env)
latndvi <- lm(ndvi_M~lat, data = lum_env)

```

# morphometric data
```{r pca morpho}

morpho <- lum_env %>% 
  dplyr::select(ID, weight.g, wing.R.mm, tail.mm, bill.depth.mm, 
                bill.culmen.mm, bill.nares.mm, bill.width.mm, Tarsometatarsus) 
morphoIDs <- morpho$ID
morpho <- morpho[,-1]
morphopca <- prcomp( ~ ., data = morpho, , na.action = na.exclude, scale.=T)

biplot(morphopca, cex = 0.5, las = 1) 

pcscores <- data.frame(ID = morphoIDs, 
                       PC1 = morphopca$x[,1], PC2 = morphopca$x[,2], 
                  PC3 = morphopca$x[,3], PC4 = morphopca$x[,4])

lum_pc <- merge(lum_env, pcscores, all = T)

ggplot(data = lum_pc, aes(x = lat, y = PC2))+
  geom_point()+
  theme_classic()

ggplot(data = lum_pc, aes(x = lat, y = Tarsometatarsus))+
  geom_point()+
  theme_classic()

tarso <- lm(Tarsometatarsus ~ lat, data = lum_pc, na.action = "na.omit")
summary(tarso)

ggplot(data = lum_pc, aes(x = bio_10, y = PC1, color = lat))+
  geom_point()+
  theme_classic()

ggplot(data = lum_pc, aes(x = srtm, y = PC2, color = lat))+
  geom_point()+
  theme_classic()

ggplot(data = lum_env, aes(x = wing.spot.L.mm, y = area_mm2_w ))+
  geom_point()+
  theme_classic()

cor.test(x=lum_env$wing.spot.L.mm, y=lum_env$area_mm2_w, method = "pearson")

```